name: Deployer


on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YCR_TOKEN }}
          
      # - name: Add private key
      #   env:
      #     ID_RSA: ${{ secrets.ID_RSA }}
      #   run: mkdir .ssh && touch .ssh/id_rsa && printf -- "$ID_RSA" > .ssh/id_rsa
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cr.yandex/crp4j94ui2o0mg26i9v8/deployer:latest

      - name: Push image to Registry
        run: docker push cr.yandex/crp4j94ui2o0mg26i9v8/deployer:latest